### ISSUE TITLE
Header with CSS Grid Layout

### ISSUE THREAD

**Issue by luguru** [sigdeletras/css-map#1]
Hi Patricio, I show you another way to make the header using CSS Grid Layout.

`/* Reset rules */`
`* {
    box-sizing: border-box;
    padding: 0;
    margin: 0;
}`

`/* Variables */`
`:root {
    /* Colors */
    --bg-header: #161925;
    --bg-header-hover: #8EA8C3;
    --font-color-nav: #f2f2f2;
    /* Fonts */
    --font-family-body: 'Montserrat', sans-serif;
}`

`/* Basic rules */`
`body {
    font-family: var(--font-family-body);
    overflow-y: hidden;
}`

`/* Nav */`
`nav {
    display: grid;
    grid-template-columns: 1fr 1fr 1fr 1fr;
    grid-auto-columns: 1fr;
    grid-auto-flow: column;
    background-color: var(--bg-header);
    -webkit-box-shadow: 0px 2px 5px 0px rgba(100, 100, 100, 1);
    -moz-box-shadow: 0px 2px 5px 0px rgba(100, 100, 100, 1);
    box-shadow: 0px 2px 5px 0px rgba(100, 100, 100, 1);
}`

`nav a {
    padding: 16px 0;
    padding: 1rem 0;
    color: var(--font-color-nav);
    text-decoration: none;
    text-align: center;
}`

`nav a:hover:not(.logo) {
    background-color: var(--bg-header-hover);
    color: black;
    font-weight: bold;
}`

`nav a.logo {
    background-color: #23395b;
    color: var(--font-color-nav);
}`

`/* Map */`
`.map {
    height: calc(100vh - 48px);
    height: calc(100vh - 3rem);
    width: 100%;
  }`

  `.ol-zoom-in:hover, .ol-zoom-out:hover {
      cursor: pointer;
  }`

**Comment by sigdeletras** [comment]
Thank you very much @luguru. I will consider your comment for future entries.

Greetings
